; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs < %s | FileCheck %s
; Check that we can lower a use of an alloca both as a deopt value (where the
; exact meaning is up to the consumer of the stackmap) and as an explicit spill
; slot used for GC.

target datalayout = "e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

declare zeroext i1 @return_i1()

; Can we handle an explicit relocation slot (in the form of an alloca) given
; to the statepoint?
define i32 addrspace(1)* @test(i32 addrspace(1)* %ptr) gc "statepoint-example" {
; CHECK-LABEL: test:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    str x30, [sp, #-16]!
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    str x0, [sp, #8]
; CHECK-NEXT:    bl return_i1
; CHECK-NEXT:  .Ltmp0:
; CHECK-NEXT:    ldr x0, [sp, #8]
; CHECK-NEXT:    ldr x30, [sp], #16
; CHECK-NEXT:    ret
entry:
  %alloca = alloca i32 addrspace(1)*, align 8
  store i32 addrspace(1)* %ptr, i32 addrspace(1)** %alloca
  call token (i64, i32, i1 ()*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_i1f(i64 0, i32 0, i1 ()* @return_i1, i32 0, i32 0, i32 0, i32 0, i32 addrspace(1)** %alloca)
  %rel = load i32 addrspace(1)*, i32 addrspace(1)** %alloca
  ret i32 addrspace(1)* %rel
}

; Can we handle an alloca as a deopt value?
define i32 addrspace(1)* @test2(i32 addrspace(1)* %ptr) gc "statepoint-example" {
; CHECK-LABEL: test2:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    str x30, [sp, #-16]!
; CHECK-NEXT:    .cfi_def_cfa_offset 16
; CHECK-NEXT:    .cfi_offset w30, -16
; CHECK-NEXT:    str x0, [sp, #8]
; CHECK-NEXT:    bl return_i1
; CHECK-NEXT:  .Ltmp1:
; CHECK-NEXT:    mov x0, xzr
; CHECK-NEXT:    ldr x30, [sp], #16
; CHECK-NEXT:    ret
entry:
  %alloca = alloca i32 addrspace(1)*, align 8
  store i32 addrspace(1)* %ptr, i32 addrspace(1)** %alloca
  call token (i64, i32, i1 ()*, i32, i32, ...) @llvm.experimental.gc.statepoint.p0f_i1f(i64 0, i32 0, i1 ()* @return_i1, i32 0, i32 0, i32 0, i32 1, i32 addrspace(1)** %alloca)
  ret i32 addrspace(1)* null
}

declare token @llvm.experimental.gc.statepoint.p0f_i1f(i64, i32, i1 ()*, i32, i32, ...)


; CHECK-LABEL: .section .llvm_stackmaps
; CHECK-NEXT:  __LLVM_StackMaps:
; Header
; CHECK-NEXT:   .byte 3
; CHECK-NEXT:   .byte 0
; CHECK-NEXT:   .hword 0
; Num Functions
; CHECK-NEXT:   .word 2
; Num LargeConstants
; CHECK-NEXT:   .word 0
; Num Callsites
; CHECK-NEXT:   .word 2

; Functions and stack size
; CHECK-NEXT:   .xword test
; CHECK-NEXT:   .xword 16
; CHECK-NEXT:   .xword 1
; CHECK-NEXT:   .xword test2
; CHECK-NEXT:   .xword 16
; CHECK-NEXT:   .xword 1

; Large Constants
; Statepoint ID only
; CHECK: .xword	0

; Callsites
; The GC one
; CHECK: .word	.Ltmp0-test
; CHECK: .hword	0
; CHECK: .hword	4
; SmallConstant (0)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	0
; SmallConstant (0)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	0
; SmallConstant (0)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	0
; Direct Spill Slot [SP+8]
; CHECK: .byte	2
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	31
; CHECK: .hword	0
; CHECK: .word	-8
; No Padding or LiveOuts
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .p2align	3

; The Deopt one
; CHECK: .word	.Ltmp1-test2
; CHECK: .hword	0
; CHECK: .hword	4
; SmallConstant (0)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	0
; SmallConstant (0)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	0
; SmallConstant (1)
; CHECK: .byte	4
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .word	1
; Direct Spill Slot [SP+8]
; CHECK: .byte	2
; CHECK: .byte	0
; CHECK: .hword 8
; CHECK: .hword	31
; CHECK: .hword	0
; CHECK: .word	8

; No Padding or LiveOuts
; CHECK: .hword	0
; CHECK: .hword	0
; CHECK: .p2align	3
